hyperskill_project:
  id: 140
  ide_files: https://cogniterra.org/media/attachments/lesson/25228/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Mon, 03 Jun 2024 19:49:28 UTC"
stages:
  - id: 758
    step: 11501
    is_completed: true
  - id: 759
    step: 11502
    is_completed: true
  - id: 760
    step: 11503
    is_completed: true
  - id: 761
    step: 11504
    is_completed: false
topics:
  0:
    - title: Computer algorithms
      theory_id: 16547
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: Complexity cases and how to use them
      theory_id: 20084
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: "Basic terms: JVM, JRE, JDK"
      theory_id: 3499
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Running programs on your computer
      theory_id: 3746
    - title: Units of information
      theory_id: 6865
    - title: Immutability
      theory_id: 7929
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: Fixed-size array
      theory_id: 20078
    - title: Dynamic array
      theory_id: 5357
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Introduction to Java
      theory_id: 38627
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 3522
    - title: Writing first program
      theory_id: 3521
    - title: Printing data
      theory_id: 3749
    - title: Types and variables
      theory_id: 3518
    - title: Comments
      theory_id: 3520
    - title: Reading user's input with Scanner
      theory_id: 9055
    - title: Coding style conventions
      theory_id: 12411
    - title: Naming variables
      theory_id: 3513
    - title: Arithmetic operations
      theory_id: 3519
    - title: Integer types and operations
      theory_id: 3565
    - title: Boolean type and operations. True and false
      theory_id: 3516
    - title: Comparing values. Relational operators
      theory_id: 3512
    - title: Conditional statement
      theory_id: 3503
    - title: One-line condition with ternary operator
      theory_id: 3506
    - title: Increment and decrement
      theory_id: 5008
    - title: While and do-while loops
      theory_id: 3498
    - title: For-loop
      theory_id: 3505
    - title: Break and continue. Branching
      theory_id: 3507
    - title: "Multiple conditions: switch"
      theory_id: 3504
    - title: Data types and their sizes
      theory_id: 3532
    - title: Type casting
      theory_id: 3510
    - title: Calling methods
      theory_id: 10973
    - title: Declaring methods
      theory_id: 10982
    - title: Method "main"
      theory_id: 3489
    - title: Functional decomposition
      theory_id: 10570
    - title: Primitive and reference types
      theory_id: 5035
    - title: Array
      theory_id: 3511
    - title: Arrays as parameters
      theory_id: 3594
    - title: Characters
      theory_id: 3514
    - title: String
      theory_id: 3523
    - title: Constants. Final variables
      theory_id: 7427
    - title: First glance at exceptions
      theory_id: 3497
    - title: Hierarchy of exceptions
      theory_id: 3570
    - title: Exception handling
      theory_id: 3552
    - title: NullPointerException
      theory_id: 1945
    - title: Iterating over arrays
      theory_id: 3602
    - title: Build tools
      theory_id: 4284
    - title: JAR files
      theory_id: 4311
    - title: "Gradle: overview"
      theory_id: 5075
    - title: Basic project with Gradle
      theory_id: 5077
    - title: Building apps using Gradle
      theory_id: 7917
    - title: "Dependency management: repositories"
      theory_id: 37189
    - title: File class
      theory_id: 3635
    - title: Managing files
      theory_id: 3648
    - title: What is object-oriented programming
      theory_id: 3614
    - title: What are bugs
      theory_id: 5504
    - title: What are databases
      theory_id: 8497
    - title: Connecting to a database with JDBC
      theory_id: 9519
    - title: "SQL: structured query language"
      theory_id: 7054
    - title: Basic data types
      theory_id: 7123
    - title: Basic CREATE statement
      theory_id: 9084
    - title: Introduction to logging
      theory_id: 5538
    - title: Debugging techniques
      theory_id: 13775
    - title: Introduction to generic programming
      theory_id: 3492
    - title: Generics and Object
      theory_id: 3493
    - title: Lambda expressions
      theory_id: 11635
    - title: Method references
      theory_id: 3620
    - title: Functional interfaces
      theory_id: 11636
    - title: What are collections
      theory_id: 3770
    - title: The Collections framework overview
      theory_id: 3624
    - title: ArrayList
      theory_id: 3567
    - title: The List interface
      theory_id: 3581
    - title: The Set interface
      theory_id: 3575
    - title: Standard functional interfaces
      theory_id: 3623
    - title: Optional
      theory_id: 9699
    - title: Ordering and total order
      theory_id: 9253
    - title: Comparator
      theory_id: 12966
    - title: Functional data processing with streams
      theory_id: 3582
    - title: Reduction methods
      theory_id: 3569
    - title: Collectors
      theory_id: 3613
    - title: Defining classes
      theory_id: 3618
    - title: Grouping classes with packages
      theory_id: 3621
    - title: Instance methods
      theory_id: 3495
    - title: Initializing new instances. Constructor
      theory_id: 3535
    - title: Access modifiers
      theory_id: 3589
    - title: Getters and setters
      theory_id: 3599
    - title: Inheritance
      theory_id: 3583
    - title: Keyword "super"
      theory_id: 3588
    - title: Objects and their properties
      theory_id: 4727
    - title: Method overriding
      theory_id: 3572
    - title: Polymorphism
      theory_id: 3587
    - title: Declaring functionality with interfaces
      theory_id: 3615
    - title: Anonymous class
      theory_id: 11896
    - title: Default methods
      theory_id: 11354
    - title: Wrapping classes. Boxing
      theory_id: 3595
    - title: Comparable
      theory_id: 14456
  1:
    - title: Intro to H2 database
      theory_id: 27725
    - title: Literals
      theory_id: 7400
    - title: Arithmetic expressions
      theory_id: 7409
    - title: Basic SELECT statement
      theory_id: 7392
    - title: SELECT FROM statement
      theory_id: 8611
    - title: The NULL value
      theory_id: 7907
    - title: Basic INSERT statement
      theory_id: 9059
    - title: Intro to MySQL
      theory_id: 16662
    - title: Results ordering
      theory_id: 8627
    - title: Basic UPDATE statement
      theory_id: 9067
    - title: JDBC Statements
      theory_id: 9955
    - title: JDBC Prepared Statements
      theory_id: 11014
    - title: Data Access Object for JDBC
      theory_id: 20188
    - title: Alter table
      theory_id: 9579
    - title: PRIMARY KEY constraint
      theory_id: 9781
    - title: Consistency constraints
      theory_id: 9587
  2:
    - title: Relational Data Model
      theory_id: 13785
    - title: Logic and comparison expressions
      theory_id: 8619
    - title: FOREIGN KEY constraint
      theory_id: 9789
  3:
    - title: Updating selected rows
      theory_id: 9603
